backend:
  name: git-gateway
  branch: main   # or your default branch

media_folder: "public/uploads"   # Where uploaded images go
public_folder: "/uploads"

collections:
  - name: "pages"
  label: "Pages"
  files:
    - file: "src/content/pages/about.md"
      label: "About Page"
      name: "about"
      fields:
        - { label: "Title", name: "title", widget: "string" }
        - { label: "Hero", name: "hero", widget: "string" }
        - { label: "Story Image", name: "story_image", widget: "image" }
        - { label: "Story Title", name: "story_title", widget: "string" }
        - { label: "Story Body", name: "story_body", widget: "markdown" }
        - label: "Values"
          name: "values"
          widget: "list"
          fields:
            - { label: "Title", name: "title", widget: "string" }
            - { label: "Description", name: "description", widget: "text" }
        - { label: "CTA Title", name: "cta_title", widget: "string" }
        - { label: "CTA Text", name: "cta_text", widget: "text" }


  - name: "projects"
    label: "Projects"
    folder: "src/content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Date", name: "date", widget: "datetime" }
  
  - name: "services"
    label: "Services"
    folder: "src/content/services"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Icon", name: "icon", widget: "string", hint: "Use a FontAwesome icon class, e.g., 'fa-solid fa-hammer'" }
      - { label: "Description", name: "description", widget: "text" } 